version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: spaceflight
        container_name: spaceflight-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        env_file: '.env.production'
        networks:
            - spaceflight
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: spaceflight-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 3306:3306
        volumes:
            - spaceflight_volume:/var/lib/mysql
        networks:
            - spaceflight

    nginx:
        image: nginx:1.17-alpine
        container_name: spaceflight-nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            - spaceflight

networks:
    spaceflight:
        driver: bridge

volumes:
    spaceflight_volume: {}
